version: '3.9'

services:
  web:
    build: .
    container_name: momfraud-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: momfraud-api
    environment:
      POSTGRES_DB: momo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bentjun25$
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
