version: '3.9'

services:
  web:
    build: .
    container_name: momofraud-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: ["/start.sh"]

  db:
    image: postgres:17
    container_name: momofraud-db
    restart: always
    environment:
      POSTGRES_DB: momo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bentjun25$
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

